apiVersion: eksctl.io/v1aplha5
kind: ClusterConfig
metadata:
	name: fargatecluster
	region: ap-southeast-1
    
fargateProfiles:
    - name: fargate-default
      selectors:
      - namespace: kube-system
      - namespace: default